### PR TITLE
Add a DTMF instrument

### PR DESCRIPTION
**Pull request by Technohacker**
This showcases the capability of GoDAW's instrument API for having instruments provide their own UI and way to play a given note. The note data for this instrument is the key on a phone keypad

### CODE REVIEW

**Review by abhinav3967 — DISMISSED** [review]
Haven't tested it but it seems correct. Now all it needs is an icon.

**Comment by Technohacker** [comment]
One with the traditional phone keypad will do :D

**Comment by Technohacker** [comment]
This PR depends on #25

**Comment by abhinav3967** [comment]
I tested both seems to be working

**Pull request merged**
